// ─────────────────────────────────────────────────────────────────────────────
// Elitez Technical SEO Doctor — GSC Fix Plan Exporter (V3)
// Generates Markdown and CSV downloads from GSCDecisionSummary.
// ─────────────────────────────────────────────────────────────────────────────

import type { GSCDecisionSummary, MatchedGSCRecord, IndexingDecisionType } from '@/types/seo';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function priEmoji(p: string): string {
  return p === 'critical' ? '🔴' : p === 'high' ? '🟠' : p === 'medium' ? '🟡' : '🔵';
}

function approvalEmoji(a: string): string {
  return a === 'safe' ? '✅ Safe' : a === 'needs-review' ? '⚠️ Needs Review' : '🚨 Needs Developer';
}

function escCsv(val: string): string {
  return `"${String(val ?? '').replace(/"/g, '""')}"`;
}

function truncate(s: string, n = 100) {
  return s.length > n ? s.slice(0, n) + '…' : s;
}

// ─── Markdown export ──────────────────────────────────────────────────────────

export function generateGSCMarkdown(summary: GSCDecisionSummary): string {
  const { records, summary: s, importedAt, fileName } = summary;
  const date = new Date(importedAt).toLocaleString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  const lines: string[] = [];

  lines.push('# GSC Indexing Fix Plan');
  lines.push(`> Generated by Elitez SEO Doctor · ${date}`);
  lines.push(`> Source file: ${fileName}`);
  lines.push('');

  // ── Summary ──────────────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total URLs imported | ${s.totalUrls} |`);
  lines.push(`| ✅ Already indexed  | ${s.indexedCount} |`);
  lines.push(`| ⚠️ Action required  | ${s.actionRequiredCount} |`);
  lines.push(`| 🔍 Matched with crawl | ${s.matchedCount} / ${s.totalUrls} |`);
  lines.push('');

  // Priority breakdown
  lines.push('## Priority Breakdown');
  lines.push('');
  lines.push(`| Priority | Count |`);
  lines.push(`|----------|-------|`);
  for (const [p, count] of Object.entries(s.priorityBreakdown)) {
    if (count > 0) lines.push(`| ${priEmoji(p)} ${p.charAt(0).toUpperCase() + p.slice(1)} | ${count} |`);
  }
  lines.push('');

  // Decision breakdown
  lines.push('## Decision Breakdown');
  lines.push('');
  lines.push(`| Decision | Count |`);
  lines.push(`|----------|-------|`);
  const sortedDecisions = Object.entries(s.decisionBreakdown)
    .sort(([, a], [, b]) => (b ?? 0) - (a ?? 0));
  for (const [d, cnt] of sortedDecisions) {
    if (cnt) lines.push(`| ${d} | ${cnt} |`);
  }
  lines.push('');

  // GSC reason breakdown
  if (Object.keys(s.reasonBreakdown).length > 0) {
    lines.push('## GSC Status Breakdown');
    lines.push('');
    lines.push(`| GSC Status | Count |`);
    lines.push(`|-----------|-------|`);
    for (const [r, cnt] of Object.entries(s.reasonBreakdown).sort(([, a], [, b]) => b - a)) {
      lines.push(`| ${r} | ${cnt} |`);
    }
    lines.push('');
  }

  // ── Detailed action list ──────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push('## Detailed Action List');
  lines.push('');

  // Group by priority
  const byPriority: Record<string, MatchedGSCRecord[]> = {
    critical: [], high: [], medium: [], low: [],
  };
  for (const r of records) {
    if (r.decision.decision !== 'Index') {
      byPriority[r.decision.priority].push(r);
    }
  }

  for (const priority of ['critical', 'high', 'medium', 'low'] as const) {
    const group = byPriority[priority];
    if (!group.length) continue;

    lines.push(`### ${priEmoji(priority)} ${priority.charAt(0).toUpperCase() + priority.slice(1)} Priority (${group.length})`);
    lines.push('');

    for (const r of group) {
      lines.push(`#### ${r.gsc.url}`);
      lines.push('');
      lines.push(`| Field | Value |`);
      lines.push(`|-------|-------|`);
      lines.push(`| **GSC Status** | ${r.gsc.reason || 'Unknown'} |`);
      lines.push(`| **Decision** | ${r.decision.decision} |`);
      lines.push(`| **Approval** | ${approvalEmoji(r.decision.approvalLevel)} |`);
      if (r.gsc.lastCrawled) lines.push(`| **Last Crawled** | ${r.gsc.lastCrawled} |`);
      if (r.crawlStatus === 'matched' && r.crawledPage) {
        lines.push(`| **HTTP Status** | ${r.crawledPage.statusCode} |`);
        lines.push(`| **Word Count** | ${r.crawledPage.wordCount} |`);
        lines.push(`| **Page Intent** | ${r.crawledPage.pageIntent} |`);
      } else {
        lines.push(`| **Crawl Status** | Not crawled by tool |`);
      }
      lines.push('');
      lines.push(`**For your team:** ${r.decision.clientExplanation}`);
      lines.push('');
      if (r.decision.likelyCauses.length) {
        lines.push('**Root causes:**');
        r.decision.likelyCauses.forEach(c => lines.push(`- ${c}`));
        lines.push('');
      }
      lines.push('**Actions:**');
      r.decision.recommendedActions.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
      lines.push('');
      lines.push('**Developer instructions:**');
      lines.push('```');
      lines.push(r.decision.developerInstructions);
      lines.push('```');
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  // ── Already indexed ───────────────────────────────────────────────────
  const indexed = records.filter(r => r.gsc.reasonCategory === 'indexed');
  if (indexed.length) {
    lines.push(`### ✅ Already Indexed (${indexed.length})`);
    lines.push('');
    lines.push('These pages are in Google\'s index and require no action.');
    lines.push('');
    indexed.forEach(r => lines.push(`- ${r.gsc.url}`));
    lines.push('');
  }

  // ── Developer task list ───────────────────────────────────────────────
  const devTasks = records.filter(r => r.decision.approvalLevel === 'needs-developer');
  if (devTasks.length) {
    lines.push('---');
    lines.push('');
    lines.push(`## 🧑‍💻 Developer Task List (${devTasks.length} URLs)`);
    lines.push('');
    lines.push('These tasks require code or server configuration changes.');
    lines.push('');
    devTasks.forEach((r, i) => {
      lines.push(`### Task ${i + 1}: ${r.decision.decision}`);
      lines.push(`**URL:** ${r.gsc.url}`);
      lines.push(`**Priority:** ${priEmoji(r.decision.priority)} ${r.decision.priority}`);
      lines.push('');
      lines.push('```');
      lines.push(r.decision.developerInstructions);
      lines.push('```');
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Report generated by [Elitez Technical SEO Doctor](https://www.elitez.asia/) — ${date}*`);

  return lines.join('\n');
}

// ─── CSV export ───────────────────────────────────────────────────────────────

export function generateGSCCSV(summary: GSCDecisionSummary): string {
  const headers = [
    'URL',
    'GSC Status',
    'GSC Category',
    'Last Crawled',
    'Decision',
    'Priority',
    'Approval Level',
    'Crawl Match',
    'HTTP Status',
    'Word Count',
    'Page Intent',
    'Has Noindex',
    'Canonical Issue',
    'Client Explanation',
    'Recommended Actions',
    'Developer Instructions',
  ];

  const rows = summary.records.map(r => {
    const p = r.crawledPage;
    return [
      escCsv(r.gsc.url),
      escCsv(r.gsc.reason),
      escCsv(r.gsc.reasonCategory),
      escCsv(r.gsc.lastCrawled),
      escCsv(r.decision.decision),
      escCsv(r.decision.priority),
      escCsv(r.decision.approvalLevel),
      escCsv(r.crawlStatus),
      escCsv(p ? String(p.statusCode) : ''),
      escCsv(p ? String(p.wordCount)  : ''),
      escCsv(p ? p.pageIntent         : ''),
      escCsv(p ? (p.noindex ? 'Yes' : 'No') : ''),
      escCsv(p ? (!p.canonicalMatchesSelf && !!p.canonical ? `→ ${p.canonical}` : 'No') : ''),
      escCsv(truncate(r.decision.clientExplanation, 200)),
      escCsv(r.decision.recommendedActions.join(' | ')),
      escCsv(truncate(r.decision.developerInstructions, 300)),
    ].join(',');
  });

  return [headers.map(escCsv).join(','), ...rows].join('\n');
}

// ─── Browser download helpers ─────────────────────────────────────────────────

export function downloadText(content: string, fileName: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadGSCMarkdown(summary: GSCDecisionSummary): void {
  const md       = generateGSCMarkdown(summary);
  const domain   = (() => {
    try {
      const u = summary.records[0]?.gsc.url;
      return u ? new URL(u).hostname.replace('www.', '') : 'report';
    } catch { return 'report'; }
  })();
  const dateStr  = new Date(summary.importedAt).toISOString().slice(0, 10);
  downloadText(md, `gsc-fix-plan-${domain}-${dateStr}.md`, 'text/markdown');
}

export function downloadGSCCSV(summary: GSCDecisionSummary): void {
  const csv      = generateGSCCSV(summary);
  const domain   = (() => {
    try {
      const u = summary.records[0]?.gsc.url;
      return u ? new URL(u).hostname.replace('www.', '') : 'report';
    } catch { return 'report'; }
  })();
  const dateStr  = new Date(summary.importedAt).toISOString().slice(0, 10);
  downloadText(csv, `gsc-fix-plan-${domain}-${dateStr}.csv`, 'text/csv');
}
